### ISSUE TITLE
Add generator to bootstrap quicker

### ISSUE THREAD

**Issue by lleger** [promptworks/guardian_trackable#1]
Great project! Had implemented something myself before but appreciated not having to do the work again.

It might be nice to include a generator with the package? Thinking the generator could create a migration and possible insert into a given schema. Would make getting started with this package a bit easier. Would be happy to take a stab at a PR if you think it’s a good idea.

Thanks again!

**Comment by rzane** [comment]
Yeah, this sounds like a great idea. A PR would be much appreciated!
